{
    'name': 'HS Custom Documents',
    'version': '1.0',
    'description': 'HS Custom Documents',
    'author': 'Comunitea',
    'website': 'https://comunitea.com',
    'license': 'AGPL-3',
    'category': 'Custom',
    'contributors': ['Comunitea ', 'Miguel Vázquez <miguel@comunitea.com>'],
    'depends': [
        'hs_field_service','report_qweb_element_page_visibility'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/paperformat.xml',
        'data/sequence.xml',
        'data/project_contract_types.xml',
        'wizard/worksheet_signature_wzd_view.xml',
        'views/project_views.xml',
        'views/res_company.xml',
        'views/res_company.xml',
        'views/project_contract_type_view.xml',
        'report/report_templates.xml',
        'report/project_work_data_sheet_report.xml',
        'report/reduced_iva_report.xml',
        'report/puresilent_contract_report.xml',
        'report/enc_contract_report.xml',
        'report/cap_contract_report.xml',
        'report/radon_contract_report.xml',
        'report/misc_contract_report.xml',
        'report/mant_puresilent_contract_report.xml',
        'report/worksheet_report.xml',
        'report/reports.xml',
    ],
    'auto_install': False,
    'installable': True,
}
